### PR TITLE
MHT with diagonal weights

### PR DESCRIPTION
**Pull request by HobigerJ**
@mtw please review

max. path dimension 10: 60.22
max. path dimension 999: 7223.33
(die files bitte als parameter uebergeben (HobigerJ-MHTHVD.cpp rmHV_10_12)

### CODE REVIEW

**Comment by mtw** [comment]
no junk files pls

**Comment by HobigerJ** [comment]
what junk files? I can only see my source code file

**Comment by mtw** [comment]
Your submission contains data from previous assignments, e.g. A0/A1/A2 etc., which should not be part of the A4 submission. It seems your repo is not in sync with the upstream master. Pls verify, fix and re-submit.

**Comment by mtw** [comment]
Approved!

**Pull request closed without merging**
